# Generated by Django 5.2.10 on 2026-01-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(verbose_name='Дата'),
        ),
    ]
