# Generated by Django 5.2.10 on 2026-01-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_alter_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialgoal',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Желаемая дата'),
        ),
    ]
